/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ClientRouteImport } from './routes/_client'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as CatalogRouteImport } from './routes/catalog'
import { Route as LoginRouteImport } from './routes/login'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as ClientDashboardRouteImport } from './routes/_client.dashboard'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as AdminAnalyticsRouteImport } from './routes/admin.analytics'
import { Route as AdminComboRouteImport } from './routes/admin.combo'
import { Route as AdminKeysRouteImport } from './routes/admin.keys'
import { Route as AdminLogsRouteImport } from './routes/admin.logs'
import { Route as AdminPayoutsRouteImport } from './routes/admin.payouts'
import { Route as AdminPlaygroundRouteImport } from './routes/admin.playground'
import { Route as AdminPricingRouteImport } from './routes/admin.pricing'
import { Route as AdminProvidersRouteImport } from './routes/admin.providers'
import { Route as AdminQuotaRouteImport } from './routes/admin.quota'
import { Route as AdminSettingsRouteImport } from './routes/admin.settings'
import { Route as AdminUsersRouteImport } from './routes/admin.users'
import { Route as CatalogIndexRouteImport } from './routes/catalog/index'
import { Route as CatalogSplatRouteImport } from './routes/catalog/$'
import { Route as ClientDashboardIndexRouteImport } from './routes/_client.dashboard.index'
import { Route as ClientDashboardAnalyticsRouteImport } from './routes/_client.dashboard.analytics'
import { Route as ClientDashboardKeysRouteImport } from './routes/_client.dashboard.keys'
import { Route as ClientDashboardMyApisRouteImport } from './routes/_client.dashboard.my-apis'
import { Route as ClientDashboardPayoutsRouteImport } from './routes/_client.dashboard.payouts'
import { Route as ClientDashboardPlaygroundRouteImport } from './routes/_client.dashboard.playground'
import { Route as ClientDashboardProfileRouteImport } from './routes/_client.dashboard.profile'
import { Route as ClientDashboardSettingsRouteImport } from './routes/_client.dashboard.settings'
import { Route as ClientDashboardUsageRouteImport } from './routes/_client.dashboard.usage'
import { Route as AdminProvidersIndexRouteImport } from './routes/admin.providers/index'
import { Route as AdminProvidersProviderIdRouteImport } from './routes/admin.providers/$providerId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ClientRoute = ClientRouteImport.update({
  id: '/_client',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const CatalogRoute = CatalogRouteImport.update({
  id: '/catalog',
  path: '/catalog',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const ClientDashboardRoute = ClientDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => ClientRoute,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAnalyticsRoute = AdminAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => AdminRoute,
} as any)
const AdminComboRoute = AdminComboRouteImport.update({
  id: '/combo',
  path: '/combo',
  getParentRoute: () => AdminRoute,
} as any)
const AdminKeysRoute = AdminKeysRouteImport.update({
  id: '/keys',
  path: '/keys',
  getParentRoute: () => AdminRoute,
} as any)
const AdminLogsRoute = AdminLogsRouteImport.update({
  id: '/logs',
  path: '/logs',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPayoutsRoute = AdminPayoutsRouteImport.update({
  id: '/payouts',
  path: '/payouts',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPlaygroundRoute = AdminPlaygroundRouteImport.update({
  id: '/playground',
  path: '/playground',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPricingRoute = AdminPricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => AdminRoute,
} as any)
const AdminProvidersRoute = AdminProvidersRouteImport.update({
  id: '/providers',
  path: '/providers',
  getParentRoute: () => AdminRoute,
} as any)
const AdminQuotaRoute = AdminQuotaRouteImport.update({
  id: '/quota',
  path: '/quota',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSettingsRoute = AdminSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AdminRoute,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AdminRoute,
} as any)
const CatalogIndexRoute = CatalogIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => CatalogRoute,
} as any)
const CatalogSplatRoute = CatalogSplatRouteImport.update({
  id: '/$',
  path: '/$',
  getParentRoute: () => CatalogRoute,
} as any)
const ClientDashboardIndexRoute = ClientDashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ClientDashboardRoute,
} as any)
const ClientDashboardAnalyticsRoute =
  ClientDashboardAnalyticsRouteImport.update({
    id: '/analytics',
    path: '/analytics',
    getParentRoute: () => ClientDashboardRoute,
  } as any)
const ClientDashboardKeysRoute = ClientDashboardKeysRouteImport.update({
  id: '/keys',
  path: '/keys',
  getParentRoute: () => ClientDashboardRoute,
} as any)
const ClientDashboardMyApisRoute = ClientDashboardMyApisRouteImport.update({
  id: '/my-apis',
  path: '/my-apis',
  getParentRoute: () => ClientDashboardRoute,
} as any)
const ClientDashboardPayoutsRoute = ClientDashboardPayoutsRouteImport.update({
  id: '/payouts',
  path: '/payouts',
  getParentRoute: () => ClientDashboardRoute,
} as any)
const ClientDashboardPlaygroundRoute =
  ClientDashboardPlaygroundRouteImport.update({
    id: '/playground',
    path: '/playground',
    getParentRoute: () => ClientDashboardRoute,
  } as any)
const ClientDashboardProfileRoute = ClientDashboardProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => ClientDashboardRoute,
} as any)
const ClientDashboardSettingsRoute = ClientDashboardSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => ClientDashboardRoute,
} as any)
const ClientDashboardUsageRoute = ClientDashboardUsageRouteImport.update({
  id: '/usage',
  path: '/usage',
  getParentRoute: () => ClientDashboardRoute,
} as any)
const AdminProvidersIndexRoute = AdminProvidersIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminProvidersRoute,
} as any)
const AdminProvidersProviderIdRoute =
  AdminProvidersProviderIdRouteImport.update({
    id: '/$providerId',
    path: '/$providerId',
    getParentRoute: () => AdminProvidersRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/catalog': typeof CatalogRouteWithChildren
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/register': typeof RegisterRoute
  '/dashboard': typeof ClientDashboardRouteWithChildren
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/combo': typeof AdminComboRoute
  '/admin/keys': typeof AdminKeysRoute
  '/admin/logs': typeof AdminLogsRoute
  '/admin/payouts': typeof AdminPayoutsRoute
  '/admin/playground': typeof AdminPlaygroundRoute
  '/admin/pricing': typeof AdminPricingRoute
  '/admin/providers': typeof AdminProvidersRouteWithChildren
  '/admin/quota': typeof AdminQuotaRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/users': typeof AdminUsersRoute
  '/catalog/$': typeof CatalogSplatRoute
  '/admin/': typeof AdminIndexRoute
  '/catalog/': typeof CatalogIndexRoute
  '/dashboard/analytics': typeof ClientDashboardAnalyticsRoute
  '/dashboard/keys': typeof ClientDashboardKeysRoute
  '/dashboard/my-apis': typeof ClientDashboardMyApisRoute
  '/dashboard/payouts': typeof ClientDashboardPayoutsRoute
  '/dashboard/playground': typeof ClientDashboardPlaygroundRoute
  '/dashboard/profile': typeof ClientDashboardProfileRoute
  '/dashboard/settings': typeof ClientDashboardSettingsRoute
  '/dashboard/usage': typeof ClientDashboardUsageRoute
  '/admin/providers/$providerId': typeof AdminProvidersProviderIdRoute
  '/dashboard/': typeof ClientDashboardIndexRoute
  '/admin/providers/': typeof AdminProvidersIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/register': typeof RegisterRoute
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/combo': typeof AdminComboRoute
  '/admin/keys': typeof AdminKeysRoute
  '/admin/logs': typeof AdminLogsRoute
  '/admin/payouts': typeof AdminPayoutsRoute
  '/admin/playground': typeof AdminPlaygroundRoute
  '/admin/pricing': typeof AdminPricingRoute
  '/admin/quota': typeof AdminQuotaRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/users': typeof AdminUsersRoute
  '/catalog/$': typeof CatalogSplatRoute
  '/admin': typeof AdminIndexRoute
  '/catalog': typeof CatalogIndexRoute
  '/dashboard/analytics': typeof ClientDashboardAnalyticsRoute
  '/dashboard/keys': typeof ClientDashboardKeysRoute
  '/dashboard/my-apis': typeof ClientDashboardMyApisRoute
  '/dashboard/payouts': typeof ClientDashboardPayoutsRoute
  '/dashboard/playground': typeof ClientDashboardPlaygroundRoute
  '/dashboard/profile': typeof ClientDashboardProfileRoute
  '/dashboard/settings': typeof ClientDashboardSettingsRoute
  '/dashboard/usage': typeof ClientDashboardUsageRoute
  '/admin/providers/$providerId': typeof AdminProvidersProviderIdRoute
  '/dashboard': typeof ClientDashboardIndexRoute
  '/admin/providers': typeof AdminProvidersIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_client': typeof ClientRouteWithChildren
  '/admin': typeof AdminRouteWithChildren
  '/catalog': typeof CatalogRouteWithChildren
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/register': typeof RegisterRoute
  '/_client/dashboard': typeof ClientDashboardRouteWithChildren
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/combo': typeof AdminComboRoute
  '/admin/keys': typeof AdminKeysRoute
  '/admin/logs': typeof AdminLogsRoute
  '/admin/payouts': typeof AdminPayoutsRoute
  '/admin/playground': typeof AdminPlaygroundRoute
  '/admin/pricing': typeof AdminPricingRoute
  '/admin/providers': typeof AdminProvidersRouteWithChildren
  '/admin/quota': typeof AdminQuotaRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/users': typeof AdminUsersRoute
  '/catalog/$': typeof CatalogSplatRoute
  '/admin/': typeof AdminIndexRoute
  '/catalog/': typeof CatalogIndexRoute
  '/_client/dashboard/analytics': typeof ClientDashboardAnalyticsRoute
  '/_client/dashboard/keys': typeof ClientDashboardKeysRoute
  '/_client/dashboard/my-apis': typeof ClientDashboardMyApisRoute
  '/_client/dashboard/payouts': typeof ClientDashboardPayoutsRoute
  '/_client/dashboard/playground': typeof ClientDashboardPlaygroundRoute
  '/_client/dashboard/profile': typeof ClientDashboardProfileRoute
  '/_client/dashboard/settings': typeof ClientDashboardSettingsRoute
  '/_client/dashboard/usage': typeof ClientDashboardUsageRoute
  '/admin/providers/$providerId': typeof AdminProvidersProviderIdRoute
  '/_client/dashboard/': typeof ClientDashboardIndexRoute
  '/admin/providers/': typeof AdminProvidersIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/catalog'
    | '/login'
    | '/onboarding'
    | '/register'
    | '/dashboard'
    | '/admin/analytics'
    | '/admin/combo'
    | '/admin/keys'
    | '/admin/logs'
    | '/admin/payouts'
    | '/admin/playground'
    | '/admin/pricing'
    | '/admin/providers'
    | '/admin/quota'
    | '/admin/settings'
    | '/admin/users'
    | '/catalog/$'
    | '/admin/'
    | '/catalog/'
    | '/dashboard/analytics'
    | '/dashboard/keys'
    | '/dashboard/my-apis'
    | '/dashboard/payouts'
    | '/dashboard/playground'
    | '/dashboard/profile'
    | '/dashboard/settings'
    | '/dashboard/usage'
    | '/admin/providers/$providerId'
    | '/dashboard/'
    | '/admin/providers/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/onboarding'
    | '/register'
    | '/admin/analytics'
    | '/admin/combo'
    | '/admin/keys'
    | '/admin/logs'
    | '/admin/payouts'
    | '/admin/playground'
    | '/admin/pricing'
    | '/admin/quota'
    | '/admin/settings'
    | '/admin/users'
    | '/catalog/$'
    | '/admin'
    | '/catalog'
    | '/dashboard/analytics'
    | '/dashboard/keys'
    | '/dashboard/my-apis'
    | '/dashboard/payouts'
    | '/dashboard/playground'
    | '/dashboard/profile'
    | '/dashboard/settings'
    | '/dashboard/usage'
    | '/admin/providers/$providerId'
    | '/dashboard'
    | '/admin/providers'
  id:
    | '__root__'
    | '/'
    | '/_client'
    | '/admin'
    | '/catalog'
    | '/login'
    | '/onboarding'
    | '/register'
    | '/_client/dashboard'
    | '/admin/analytics'
    | '/admin/combo'
    | '/admin/keys'
    | '/admin/logs'
    | '/admin/payouts'
    | '/admin/playground'
    | '/admin/pricing'
    | '/admin/providers'
    | '/admin/quota'
    | '/admin/settings'
    | '/admin/users'
    | '/catalog/$'
    | '/admin/'
    | '/catalog/'
    | '/_client/dashboard/analytics'
    | '/_client/dashboard/keys'
    | '/_client/dashboard/my-apis'
    | '/_client/dashboard/payouts'
    | '/_client/dashboard/playground'
    | '/_client/dashboard/profile'
    | '/_client/dashboard/settings'
    | '/_client/dashboard/usage'
    | '/admin/providers/$providerId'
    | '/_client/dashboard/'
    | '/admin/providers/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ClientRoute: typeof ClientRouteWithChildren
  AdminRoute: typeof AdminRouteWithChildren
  CatalogRoute: typeof CatalogRouteWithChildren
  LoginRoute: typeof LoginRoute
  OnboardingRoute: typeof OnboardingRoute
  RegisterRoute: typeof RegisterRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_client': {
      id: '/_client'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof ClientRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/catalog': {
      id: '/catalog'
      path: '/catalog'
      fullPath: '/catalog'
      preLoaderRoute: typeof CatalogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_client/dashboard': {
      id: '/_client/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof ClientDashboardRouteImport
      parentRoute: typeof ClientRoute
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/analytics': {
      id: '/admin/analytics'
      path: '/analytics'
      fullPath: '/admin/analytics'
      preLoaderRoute: typeof AdminAnalyticsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/combo': {
      id: '/admin/combo'
      path: '/combo'
      fullPath: '/admin/combo'
      preLoaderRoute: typeof AdminComboRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/keys': {
      id: '/admin/keys'
      path: '/keys'
      fullPath: '/admin/keys'
      preLoaderRoute: typeof AdminKeysRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/logs': {
      id: '/admin/logs'
      path: '/logs'
      fullPath: '/admin/logs'
      preLoaderRoute: typeof AdminLogsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/payouts': {
      id: '/admin/payouts'
      path: '/payouts'
      fullPath: '/admin/payouts'
      preLoaderRoute: typeof AdminPayoutsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/playground': {
      id: '/admin/playground'
      path: '/playground'
      fullPath: '/admin/playground'
      preLoaderRoute: typeof AdminPlaygroundRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/pricing': {
      id: '/admin/pricing'
      path: '/pricing'
      fullPath: '/admin/pricing'
      preLoaderRoute: typeof AdminPricingRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/providers': {
      id: '/admin/providers'
      path: '/providers'
      fullPath: '/admin/providers'
      preLoaderRoute: typeof AdminProvidersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/quota': {
      id: '/admin/quota'
      path: '/quota'
      fullPath: '/admin/quota'
      preLoaderRoute: typeof AdminQuotaRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/settings': {
      id: '/admin/settings'
      path: '/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AdminSettingsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/users': {
      id: '/admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/catalog/': {
      id: '/catalog/'
      path: '/'
      fullPath: '/catalog/'
      preLoaderRoute: typeof CatalogIndexRouteImport
      parentRoute: typeof CatalogRoute
    }
    '/catalog/$': {
      id: '/catalog/$'
      path: '/$'
      fullPath: '/catalog/$'
      preLoaderRoute: typeof CatalogSplatRouteImport
      parentRoute: typeof CatalogRoute
    }
    '/_client/dashboard/': {
      id: '/_client/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof ClientDashboardIndexRouteImport
      parentRoute: typeof ClientDashboardRoute
    }
    '/_client/dashboard/analytics': {
      id: '/_client/dashboard/analytics'
      path: '/analytics'
      fullPath: '/dashboard/analytics'
      preLoaderRoute: typeof ClientDashboardAnalyticsRouteImport
      parentRoute: typeof ClientDashboardRoute
    }
    '/_client/dashboard/keys': {
      id: '/_client/dashboard/keys'
      path: '/keys'
      fullPath: '/dashboard/keys'
      preLoaderRoute: typeof ClientDashboardKeysRouteImport
      parentRoute: typeof ClientDashboardRoute
    }
    '/_client/dashboard/my-apis': {
      id: '/_client/dashboard/my-apis'
      path: '/my-apis'
      fullPath: '/dashboard/my-apis'
      preLoaderRoute: typeof ClientDashboardMyApisRouteImport
      parentRoute: typeof ClientDashboardRoute
    }
    '/_client/dashboard/payouts': {
      id: '/_client/dashboard/payouts'
      path: '/payouts'
      fullPath: '/dashboard/payouts'
      preLoaderRoute: typeof ClientDashboardPayoutsRouteImport
      parentRoute: typeof ClientDashboardRoute
    }
    '/_client/dashboard/playground': {
      id: '/_client/dashboard/playground'
      path: '/playground'
      fullPath: '/dashboard/playground'
      preLoaderRoute: typeof ClientDashboardPlaygroundRouteImport
      parentRoute: typeof ClientDashboardRoute
    }
    '/_client/dashboard/profile': {
      id: '/_client/dashboard/profile'
      path: '/profile'
      fullPath: '/dashboard/profile'
      preLoaderRoute: typeof ClientDashboardProfileRouteImport
      parentRoute: typeof ClientDashboardRoute
    }
    '/_client/dashboard/settings': {
      id: '/_client/dashboard/settings'
      path: '/settings'
      fullPath: '/dashboard/settings'
      preLoaderRoute: typeof ClientDashboardSettingsRouteImport
      parentRoute: typeof ClientDashboardRoute
    }
    '/_client/dashboard/usage': {
      id: '/_client/dashboard/usage'
      path: '/usage'
      fullPath: '/dashboard/usage'
      preLoaderRoute: typeof ClientDashboardUsageRouteImport
      parentRoute: typeof ClientDashboardRoute
    }
    '/admin/providers/': {
      id: '/admin/providers/'
      path: '/'
      fullPath: '/admin/providers/'
      preLoaderRoute: typeof AdminProvidersIndexRouteImport
      parentRoute: typeof AdminProvidersRoute
    }
    '/admin/providers/$providerId': {
      id: '/admin/providers/$providerId'
      path: '/$providerId'
      fullPath: '/admin/providers/$providerId'
      preLoaderRoute: typeof AdminProvidersProviderIdRouteImport
      parentRoute: typeof AdminProvidersRoute
    }
  }
}

interface ClientDashboardRouteChildren {
  ClientDashboardAnalyticsRoute: typeof ClientDashboardAnalyticsRoute
  ClientDashboardKeysRoute: typeof ClientDashboardKeysRoute
  ClientDashboardMyApisRoute: typeof ClientDashboardMyApisRoute
  ClientDashboardPayoutsRoute: typeof ClientDashboardPayoutsRoute
  ClientDashboardPlaygroundRoute: typeof ClientDashboardPlaygroundRoute
  ClientDashboardProfileRoute: typeof ClientDashboardProfileRoute
  ClientDashboardSettingsRoute: typeof ClientDashboardSettingsRoute
  ClientDashboardUsageRoute: typeof ClientDashboardUsageRoute
  ClientDashboardIndexRoute: typeof ClientDashboardIndexRoute
}

const ClientDashboardRouteChildren: ClientDashboardRouteChildren = {
  ClientDashboardAnalyticsRoute: ClientDashboardAnalyticsRoute,
  ClientDashboardKeysRoute: ClientDashboardKeysRoute,
  ClientDashboardMyApisRoute: ClientDashboardMyApisRoute,
  ClientDashboardPayoutsRoute: ClientDashboardPayoutsRoute,
  ClientDashboardPlaygroundRoute: ClientDashboardPlaygroundRoute,
  ClientDashboardProfileRoute: ClientDashboardProfileRoute,
  ClientDashboardSettingsRoute: ClientDashboardSettingsRoute,
  ClientDashboardUsageRoute: ClientDashboardUsageRoute,
  ClientDashboardIndexRoute: ClientDashboardIndexRoute,
}

const ClientDashboardRouteWithChildren = ClientDashboardRoute._addFileChildren(
  ClientDashboardRouteChildren,
)

interface ClientRouteChildren {
  ClientDashboardRoute: typeof ClientDashboardRouteWithChildren
}

const ClientRouteChildren: ClientRouteChildren = {
  ClientDashboardRoute: ClientDashboardRouteWithChildren,
}

const ClientRouteWithChildren =
  ClientRoute._addFileChildren(ClientRouteChildren)

interface AdminProvidersRouteChildren {
  AdminProvidersProviderIdRoute: typeof AdminProvidersProviderIdRoute
  AdminProvidersIndexRoute: typeof AdminProvidersIndexRoute
}

const AdminProvidersRouteChildren: AdminProvidersRouteChildren = {
  AdminProvidersProviderIdRoute: AdminProvidersProviderIdRoute,
  AdminProvidersIndexRoute: AdminProvidersIndexRoute,
}

const AdminProvidersRouteWithChildren = AdminProvidersRoute._addFileChildren(
  AdminProvidersRouteChildren,
)

interface AdminRouteChildren {
  AdminAnalyticsRoute: typeof AdminAnalyticsRoute
  AdminComboRoute: typeof AdminComboRoute
  AdminKeysRoute: typeof AdminKeysRoute
  AdminLogsRoute: typeof AdminLogsRoute
  AdminPayoutsRoute: typeof AdminPayoutsRoute
  AdminPlaygroundRoute: typeof AdminPlaygroundRoute
  AdminPricingRoute: typeof AdminPricingRoute
  AdminProvidersRoute: typeof AdminProvidersRouteWithChildren
  AdminQuotaRoute: typeof AdminQuotaRoute
  AdminSettingsRoute: typeof AdminSettingsRoute
  AdminUsersRoute: typeof AdminUsersRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminAnalyticsRoute: AdminAnalyticsRoute,
  AdminComboRoute: AdminComboRoute,
  AdminKeysRoute: AdminKeysRoute,
  AdminLogsRoute: AdminLogsRoute,
  AdminPayoutsRoute: AdminPayoutsRoute,
  AdminPlaygroundRoute: AdminPlaygroundRoute,
  AdminPricingRoute: AdminPricingRoute,
  AdminProvidersRoute: AdminProvidersRouteWithChildren,
  AdminQuotaRoute: AdminQuotaRoute,
  AdminSettingsRoute: AdminSettingsRoute,
  AdminUsersRoute: AdminUsersRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface CatalogRouteChildren {
  CatalogSplatRoute: typeof CatalogSplatRoute
  CatalogIndexRoute: typeof CatalogIndexRoute
}

const CatalogRouteChildren: CatalogRouteChildren = {
  CatalogSplatRoute: CatalogSplatRoute,
  CatalogIndexRoute: CatalogIndexRoute,
}

const CatalogRouteWithChildren =
  CatalogRoute._addFileChildren(CatalogRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ClientRoute: ClientRouteWithChildren,
  AdminRoute: AdminRouteWithChildren,
  CatalogRoute: CatalogRouteWithChildren,
  LoginRoute: LoginRoute,
  OnboardingRoute: OnboardingRoute,
  RegisterRoute: RegisterRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
