/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as ClientRouteImport } from './routes/_client'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CatalogRouteImport } from './routes/catalog'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as AdminAnalyticsRouteImport } from './routes/admin.analytics'
import { Route as AdminComboRouteImport } from './routes/admin.combo'
import { Route as AdminKeysRouteImport } from './routes/admin.keys'
import { Route as AdminLogsRouteImport } from './routes/admin.logs'
import { Route as AdminPricingRouteImport } from './routes/admin.pricing'
import { Route as AdminProvidersRouteImport } from './routes/admin.providers'
import { Route as AdminQuotaRouteImport } from './routes/admin.quota'
import { Route as AdminSettingsRouteImport } from './routes/admin.settings'
import { Route as ClientDashboardRouteImport } from './routes/_client.dashboard'
import { Route as ClientDashboardIndexRouteImport } from './routes/_client.dashboard.index'
import { Route as ClientDashboardKeysRouteImport } from './routes/_client.dashboard.keys'
import { Route as ClientDashboardUsageRouteImport } from './routes/_client.dashboard.usage'
import { Route as ClientDashboardMyApisRouteImport } from './routes/_client.dashboard.my-apis'
import { Route as LoginRouteImport } from './routes/login'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as AdminProvidersIndexRouteImport } from './routes/admin.providers/index'
import { Route as AdminProvidersProviderIdRouteImport } from './routes/admin.providers/$providerId'

const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const ClientRoute = ClientRouteImport.update({
  id: '/_client',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CatalogRoute = CatalogRouteImport.update({
  id: '/catalog',
  path: '/catalog',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAnalyticsRoute = AdminAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => AdminRoute,
} as any)
const AdminComboRoute = AdminComboRouteImport.update({
  id: '/combo',
  path: '/combo',
  getParentRoute: () => AdminRoute,
} as any)
const AdminKeysRoute = AdminKeysRouteImport.update({
  id: '/keys',
  path: '/keys',
  getParentRoute: () => AdminRoute,
} as any)
const AdminLogsRoute = AdminLogsRouteImport.update({
  id: '/logs',
  path: '/logs',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPricingRoute = AdminPricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => AdminRoute,
} as any)
const AdminProvidersRoute = AdminProvidersRouteImport.update({
  id: '/providers',
  path: '/providers',
  getParentRoute: () => AdminRoute,
} as any)
const AdminQuotaRoute = AdminQuotaRouteImport.update({
  id: '/quota',
  path: '/quota',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSettingsRoute = AdminSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AdminRoute,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const ClientDashboardRoute = ClientDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => ClientRoute,
} as any)
const ClientDashboardIndexRoute = ClientDashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ClientDashboardRoute,
} as any)
const ClientDashboardKeysRoute = ClientDashboardKeysRouteImport.update({
  id: '/keys',
  path: '/keys',
  getParentRoute: () => ClientDashboardRoute,
} as any)
const ClientDashboardUsageRoute = ClientDashboardUsageRouteImport.update({
  id: '/usage',
  path: '/usage',
  getParentRoute: () => ClientDashboardRoute,
} as any)
const ClientDashboardMyApisRoute = ClientDashboardMyApisRouteImport.update({
  id: '/my-apis',
  path: '/my-apis',
  getParentRoute: () => ClientDashboardRoute,
} as any)
const AdminProvidersIndexRoute = AdminProvidersIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminProvidersRoute,
} as any)
const AdminProvidersProviderIdRoute = AdminProvidersProviderIdRouteImport.update({
  id: '/$providerId',
  path: '/$providerId',
  getParentRoute: () => AdminProvidersRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/catalog': typeof CatalogRoute
  '/admin': typeof AdminRouteWithChildren
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/onboarding': typeof OnboardingRoute
  '/dashboard': typeof ClientDashboardRouteWithChildren
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/combo': typeof AdminComboRoute
  '/admin/keys': typeof AdminKeysRoute
  '/admin/logs': typeof AdminLogsRoute
  '/admin/pricing': typeof AdminPricingRoute
  '/admin/providers': typeof AdminProvidersRouteWithChildren
  '/admin/quota': typeof AdminQuotaRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/': typeof AdminIndexRoute
  '/dashboard/': typeof ClientDashboardIndexRoute
  '/dashboard/keys': typeof ClientDashboardKeysRoute
  '/dashboard/usage': typeof ClientDashboardUsageRoute
  '/dashboard/my-apis': typeof ClientDashboardMyApisRoute
  '/admin/providers/': typeof AdminProvidersIndexRoute
  '/admin/providers/$providerId': typeof AdminProvidersProviderIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/catalog': typeof CatalogRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/onboarding': typeof OnboardingRoute
  '/admin': typeof AdminIndexRoute
  '/dashboard': typeof ClientDashboardIndexRoute
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/combo': typeof AdminComboRoute
  '/admin/keys': typeof AdminKeysRoute
  '/admin/logs': typeof AdminLogsRoute
  '/admin/pricing': typeof AdminPricingRoute
  '/admin/quota': typeof AdminQuotaRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/dashboard/keys': typeof ClientDashboardKeysRoute
  '/dashboard/usage': typeof ClientDashboardUsageRoute
  '/dashboard/my-apis': typeof ClientDashboardMyApisRoute
  '/admin/providers': typeof AdminProvidersIndexRoute
  '/admin/providers/$providerId': typeof AdminProvidersProviderIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/catalog': typeof CatalogRoute
  '/admin': typeof AdminRouteWithChildren
  '/_client': typeof ClientRouteWithChildren
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/onboarding': typeof OnboardingRoute
  '/admin/': typeof AdminIndexRoute
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/combo': typeof AdminComboRoute
  '/admin/keys': typeof AdminKeysRoute
  '/admin/logs': typeof AdminLogsRoute
  '/admin/pricing': typeof AdminPricingRoute
  '/admin/providers': typeof AdminProvidersRouteWithChildren
  '/admin/quota': typeof AdminQuotaRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/_client/dashboard': typeof ClientDashboardRouteWithChildren
  '/_client/dashboard/': typeof ClientDashboardIndexRoute
  '/_client/dashboard/keys': typeof ClientDashboardKeysRoute
  '/_client/dashboard/usage': typeof ClientDashboardUsageRoute
  '/_client/dashboard/my-apis': typeof ClientDashboardMyApisRoute
  '/admin/providers/': typeof AdminProvidersIndexRoute
  '/admin/providers/$providerId': typeof AdminProvidersProviderIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/catalog'
    | '/admin'
    | '/login'
    | '/register'
    | '/onboarding'
    | '/dashboard'
    | '/admin/analytics'
    | '/admin/combo'
    | '/admin/keys'
    | '/admin/logs'
    | '/admin/pricing'
    | '/admin/providers'
    | '/admin/quota'
    | '/admin/settings'
    | '/admin/'
    | '/dashboard/'
    | '/dashboard/keys'
    | '/dashboard/usage'
    | '/dashboard/my-apis'
    | '/admin/providers/'
    | '/admin/providers/$providerId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/catalog'
    | '/login'
    | '/register'
    | '/onboarding'
    | '/admin'
    | '/dashboard'
    | '/admin/analytics'
    | '/admin/combo'
    | '/admin/keys'
    | '/admin/logs'
    | '/admin/pricing'
    | '/admin/quota'
    | '/admin/settings'
    | '/dashboard/keys'
    | '/dashboard/usage'
    | '/dashboard/my-apis'
    | '/admin/providers'
    | '/admin/providers/$providerId'
  id:
    | '__root__'
    | '/'
    | '/catalog'
    | '/admin'
    | '/_client'
    | '/login'
    | '/register'
    | '/onboarding'
    | '/admin/'
    | '/admin/analytics'
    | '/admin/combo'
    | '/admin/keys'
    | '/admin/logs'
    | '/admin/pricing'
    | '/admin/providers'
    | '/admin/quota'
    | '/admin/settings'
    | '/_client/dashboard'
    | '/_client/dashboard/'
    | '/_client/dashboard/keys'
    | '/_client/dashboard/usage'
    | '/_client/dashboard/my-apis'
    | '/admin/providers/'
    | '/admin/providers/$providerId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CatalogRoute: typeof CatalogRoute
  AdminRoute: typeof AdminRouteWithChildren
  ClientRoute: typeof ClientRouteWithChildren
  LoginRoute: typeof LoginRoute
  RegisterRoute: typeof RegisterRoute
  OnboardingRoute: typeof OnboardingRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_client': {
      id: '/_client'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof ClientRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/catalog': {
      id: '/catalog'
      path: '/catalog'
      fullPath: '/catalog'
      preLoaderRoute: typeof CatalogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/analytics': {
      id: '/admin/analytics'
      path: '/analytics'
      fullPath: '/admin/analytics'
      preLoaderRoute: typeof AdminAnalyticsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/combo': {
      id: '/admin/combo'
      path: '/combo'
      fullPath: '/admin/combo'
      preLoaderRoute: typeof AdminComboRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/keys': {
      id: '/admin/keys'
      path: '/keys'
      fullPath: '/admin/keys'
      preLoaderRoute: typeof AdminKeysRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/logs': {
      id: '/admin/logs'
      path: '/logs'
      fullPath: '/admin/logs'
      preLoaderRoute: typeof AdminLogsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/pricing': {
      id: '/admin/pricing'
      path: '/pricing'
      fullPath: '/admin/pricing'
      preLoaderRoute: typeof AdminPricingRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/providers': {
      id: '/admin/providers'
      path: '/providers'
      fullPath: '/admin/providers'
      preLoaderRoute: typeof AdminProvidersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/quota': {
      id: '/admin/quota'
      path: '/quota'
      fullPath: '/admin/quota'
      preLoaderRoute: typeof AdminQuotaRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/settings': {
      id: '/admin/settings'
      path: '/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AdminSettingsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_client/dashboard': {
      id: '/_client/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof ClientDashboardRouteImport
      parentRoute: typeof ClientRoute
    }
    '/_client/dashboard/': {
      id: '/_client/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof ClientDashboardIndexRouteImport
      parentRoute: typeof ClientDashboardRoute
    }
    '/_client/dashboard/keys': {
      id: '/_client/dashboard/keys'
      path: '/keys'
      fullPath: '/dashboard/keys'
      preLoaderRoute: typeof ClientDashboardKeysRouteImport
      parentRoute: typeof ClientDashboardRoute
    }
    '/_client/dashboard/usage': {
      id: '/_client/dashboard/usage'
      path: '/usage'
      fullPath: '/dashboard/usage'
      preLoaderRoute: typeof ClientDashboardUsageRouteImport
      parentRoute: typeof ClientDashboardRoute
    }
    '/_client/dashboard/my-apis': {
      id: '/_client/dashboard/my-apis'
      path: '/my-apis'
      fullPath: '/dashboard/my-apis'
      preLoaderRoute: typeof ClientDashboardMyApisRouteImport
      parentRoute: typeof ClientDashboardRoute
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/providers/': {
      id: '/admin/providers/'
      path: '/'
      fullPath: '/admin/providers/'
      preLoaderRoute: typeof AdminProvidersIndexRouteImport
      parentRoute: typeof AdminProvidersRoute
    }
    '/admin/providers/$providerId': {
      id: '/admin/providers/$providerId'
      path: '/$providerId'
      fullPath: '/admin/providers/$providerId'
      preLoaderRoute: typeof AdminProvidersProviderIdRouteImport
      parentRoute: typeof AdminProvidersRoute
    }
  }
}

interface AdminProvidersRouteChildren {
  AdminProvidersIndexRoute: typeof AdminProvidersIndexRoute
  AdminProvidersProviderIdRoute: typeof AdminProvidersProviderIdRoute
}

const AdminProvidersRouteChildren: AdminProvidersRouteChildren = {
  AdminProvidersIndexRoute: AdminProvidersIndexRoute,
  AdminProvidersProviderIdRoute: AdminProvidersProviderIdRoute,
}

const AdminProvidersRouteWithChildren = AdminProvidersRoute._addFileChildren(
  AdminProvidersRouteChildren,
)

interface AdminRouteChildren {
  AdminIndexRoute: typeof AdminIndexRoute
  AdminAnalyticsRoute: typeof AdminAnalyticsRoute
  AdminComboRoute: typeof AdminComboRoute
  AdminKeysRoute: typeof AdminKeysRoute
  AdminLogsRoute: typeof AdminLogsRoute
  AdminPricingRoute: typeof AdminPricingRoute
  AdminProvidersRoute: typeof AdminProvidersRouteWithChildren
  AdminQuotaRoute: typeof AdminQuotaRoute
  AdminSettingsRoute: typeof AdminSettingsRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminIndexRoute: AdminIndexRoute,
  AdminAnalyticsRoute: AdminAnalyticsRoute,
  AdminComboRoute: AdminComboRoute,
  AdminKeysRoute: AdminKeysRoute,
  AdminLogsRoute: AdminLogsRoute,
  AdminPricingRoute: AdminPricingRoute,
  AdminProvidersRoute: AdminProvidersRouteWithChildren,
  AdminQuotaRoute: AdminQuotaRoute,
  AdminSettingsRoute: AdminSettingsRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface ClientDashboardRouteChildren {
  ClientDashboardIndexRoute: typeof ClientDashboardIndexRoute
  ClientDashboardKeysRoute: typeof ClientDashboardKeysRoute
  ClientDashboardUsageRoute: typeof ClientDashboardUsageRoute
  ClientDashboardMyApisRoute: typeof ClientDashboardMyApisRoute
}

const ClientDashboardRouteChildren: ClientDashboardRouteChildren = {
  ClientDashboardIndexRoute: ClientDashboardIndexRoute,
  ClientDashboardKeysRoute: ClientDashboardKeysRoute,
  ClientDashboardUsageRoute: ClientDashboardUsageRoute,
  ClientDashboardMyApisRoute: ClientDashboardMyApisRoute,
}

const ClientDashboardRouteWithChildren = ClientDashboardRoute._addFileChildren(
  ClientDashboardRouteChildren,
)

interface ClientRouteChildren {
  ClientDashboardRoute: typeof ClientDashboardRouteWithChildren
}

const ClientRouteChildren: ClientRouteChildren = {
  ClientDashboardRoute: ClientDashboardRouteWithChildren,
}

const ClientRouteWithChildren = ClientRoute._addFileChildren(ClientRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CatalogRoute: CatalogRoute,
  AdminRoute: AdminRouteWithChildren,
  ClientRoute: ClientRouteWithChildren,
  LoginRoute: LoginRoute,
  RegisterRoute: RegisterRoute,
  OnboardingRoute: OnboardingRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
