/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AdminRouteImport } from './routes/_admin'
import { Route as ClientRouteImport } from './routes/_client'
import { Route as AdminIndexRouteImport } from './routes/_admin.index'
import { Route as AdminAnalyticsRouteImport } from './routes/_admin.analytics'
import { Route as AdminComboRouteImport } from './routes/_admin.combo'
import { Route as AdminKeysRouteImport } from './routes/_admin.keys'
import { Route as AdminLogsRouteImport } from './routes/_admin.logs'
import { Route as AdminProvidersRouteImport } from './routes/_admin.providers'
import { Route as AdminQuotaRouteImport } from './routes/_admin.quota'
import { Route as AdminSettingsRouteImport } from './routes/_admin.settings'
import { Route as ClientDashboardRouteImport } from './routes/_client.dashboard'
import { Route as ClientDashboardIndexRouteImport } from './routes/_client.dashboard.index'
import { Route as ClientDashboardKeysRouteImport } from './routes/_client.dashboard.keys'
import { Route as ClientDashboardUsageRouteImport } from './routes/_client.dashboard.usage'
import { Route as LoginRouteImport } from './routes/login'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as AdminProvidersIndexRouteImport } from './routes/_admin.providers/index'
import { Route as AdminProvidersProviderIdRouteImport } from './routes/_admin.providers/$providerId'

const AdminRoute = AdminRouteImport.update({
  id: '/_admin',
  getParentRoute: () => rootRouteImport,
} as any)
const ClientRoute = ClientRouteImport.update({
  id: '/_client',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAnalyticsRoute = AdminAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => AdminRoute,
} as any)
const AdminComboRoute = AdminComboRouteImport.update({
  id: '/combo',
  path: '/combo',
  getParentRoute: () => AdminRoute,
} as any)
const AdminKeysRoute = AdminKeysRouteImport.update({
  id: '/keys',
  path: '/keys',
  getParentRoute: () => AdminRoute,
} as any)
const AdminLogsRoute = AdminLogsRouteImport.update({
  id: '/logs',
  path: '/logs',
  getParentRoute: () => AdminRoute,
} as any)
const AdminProvidersRoute = AdminProvidersRouteImport.update({
  id: '/providers',
  path: '/providers',
  getParentRoute: () => AdminRoute,
} as any)
const AdminQuotaRoute = AdminQuotaRouteImport.update({
  id: '/quota',
  path: '/quota',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSettingsRoute = AdminSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AdminRoute,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const ClientDashboardRoute = ClientDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => ClientRoute,
} as any)
const ClientDashboardIndexRoute = ClientDashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ClientDashboardRoute,
} as any)
const ClientDashboardKeysRoute = ClientDashboardKeysRouteImport.update({
  id: '/keys',
  path: '/keys',
  getParentRoute: () => ClientDashboardRoute,
} as any)
const ClientDashboardUsageRoute = ClientDashboardUsageRouteImport.update({
  id: '/usage',
  path: '/usage',
  getParentRoute: () => ClientDashboardRoute,
} as any)
const AdminProvidersIndexRoute = AdminProvidersIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminProvidersRoute,
} as any)
const AdminProvidersProviderIdRoute = AdminProvidersProviderIdRouteImport.update({
  id: '/$providerId',
  path: '/$providerId',
  getParentRoute: () => AdminProvidersRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AdminIndexRoute
  '/analytics': typeof AdminAnalyticsRoute
  '/combo': typeof AdminComboRoute
  '/keys': typeof AdminKeysRoute
  '/logs': typeof AdminLogsRoute
  '/providers': typeof AdminProvidersRouteWithChildren
  '/quota': typeof AdminQuotaRoute
  '/settings': typeof AdminSettingsRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/dashboard': typeof ClientDashboardRouteWithChildren
  '/providers/$providerId': typeof AdminProvidersProviderIdRoute
  '/providers/': typeof AdminProvidersIndexRoute
  '/dashboard/': typeof ClientDashboardIndexRoute
  '/dashboard/keys': typeof ClientDashboardKeysRoute
  '/dashboard/usage': typeof ClientDashboardUsageRoute
}
export interface FileRoutesByTo {
  '/': typeof AdminIndexRoute
  '/analytics': typeof AdminAnalyticsRoute
  '/combo': typeof AdminComboRoute
  '/keys': typeof AdminKeysRoute
  '/logs': typeof AdminLogsRoute
  '/quota': typeof AdminQuotaRoute
  '/settings': typeof AdminSettingsRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/providers/$providerId': typeof AdminProvidersProviderIdRoute
  '/providers': typeof AdminProvidersIndexRoute
  '/dashboard': typeof ClientDashboardIndexRoute
  '/dashboard/keys': typeof ClientDashboardKeysRoute
  '/dashboard/usage': typeof ClientDashboardUsageRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_admin': typeof AdminRouteWithChildren
  '/_admin/': typeof AdminIndexRoute
  '/_admin/analytics': typeof AdminAnalyticsRoute
  '/_admin/combo': typeof AdminComboRoute
  '/_admin/keys': typeof AdminKeysRoute
  '/_admin/logs': typeof AdminLogsRoute
  '/_admin/providers': typeof AdminProvidersRouteWithChildren
  '/_admin/quota': typeof AdminQuotaRoute
  '/_admin/settings': typeof AdminSettingsRoute
  '/_client': typeof ClientRouteWithChildren
  '/_client/dashboard': typeof ClientDashboardRouteWithChildren
  '/_client/dashboard/': typeof ClientDashboardIndexRoute
  '/_client/dashboard/keys': typeof ClientDashboardKeysRoute
  '/_client/dashboard/usage': typeof ClientDashboardUsageRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/_admin/providers/': typeof AdminProvidersIndexRoute
  '/_admin/providers/$providerId': typeof AdminProvidersProviderIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/analytics'
    | '/combo'
    | '/keys'
    | '/logs'
    | '/providers'
    | '/quota'
    | '/settings'
    | '/login'
    | '/register'
    | '/dashboard'
    | '/providers/$providerId'
    | '/providers/'
    | '/dashboard/'
    | '/dashboard/keys'
    | '/dashboard/usage'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/analytics'
    | '/combo'
    | '/keys'
    | '/logs'
    | '/quota'
    | '/settings'
    | '/login'
    | '/register'
    | '/providers/$providerId'
    | '/providers'
    | '/dashboard'
    | '/dashboard/keys'
    | '/dashboard/usage'
  id:
    | '__root__'
    | '/_admin'
    | '/_admin/'
    | '/_admin/analytics'
    | '/_admin/combo'
    | '/_admin/keys'
    | '/_admin/logs'
    | '/_admin/providers'
    | '/_admin/quota'
    | '/_admin/settings'
    | '/_client'
    | '/_client/dashboard'
    | '/_client/dashboard/'
    | '/_client/dashboard/keys'
    | '/_client/dashboard/usage'
    | '/login'
    | '/register'
    | '/_admin/providers/'
    | '/_admin/providers/$providerId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AdminRoute: typeof AdminRouteWithChildren
  ClientRoute: typeof ClientRouteWithChildren
  LoginRoute: typeof LoginRoute
  RegisterRoute: typeof RegisterRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_admin': {
      id: '/_admin'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_admin/': {
      id: '/_admin/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/analytics': {
      id: '/_admin/analytics'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof AdminAnalyticsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/combo': {
      id: '/_admin/combo'
      path: '/combo'
      fullPath: '/combo'
      preLoaderRoute: typeof AdminComboRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/keys': {
      id: '/_admin/keys'
      path: '/keys'
      fullPath: '/keys'
      preLoaderRoute: typeof AdminKeysRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/logs': {
      id: '/_admin/logs'
      path: '/logs'
      fullPath: '/logs'
      preLoaderRoute: typeof AdminLogsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/providers': {
      id: '/_admin/providers'
      path: '/providers'
      fullPath: '/providers'
      preLoaderRoute: typeof AdminProvidersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/quota': {
      id: '/_admin/quota'
      path: '/quota'
      fullPath: '/quota'
      preLoaderRoute: typeof AdminQuotaRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/settings': {
      id: '/_admin/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AdminSettingsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/providers/': {
      id: '/_admin/providers/'
      path: '/'
      fullPath: '/providers/'
      preLoaderRoute: typeof AdminProvidersIndexRouteImport
      parentRoute: typeof AdminProvidersRoute
    }
    '/_admin/providers/$providerId': {
      id: '/_admin/providers/$providerId'
      path: '/$providerId'
      fullPath: '/providers/$providerId'
      preLoaderRoute: typeof AdminProvidersProviderIdRouteImport
      parentRoute: typeof AdminProvidersRoute
    }
    '/_client': {
      id: '/_client'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof ClientRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_client/dashboard': {
      id: '/_client/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof ClientDashboardRouteImport
      parentRoute: typeof ClientRoute
    }
    '/_client/dashboard/': {
      id: '/_client/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof ClientDashboardIndexRouteImport
      parentRoute: typeof ClientDashboardRoute
    }
    '/_client/dashboard/keys': {
      id: '/_client/dashboard/keys'
      path: '/keys'
      fullPath: '/dashboard/keys'
      preLoaderRoute: typeof ClientDashboardKeysRouteImport
      parentRoute: typeof ClientDashboardRoute
    }
    '/_client/dashboard/usage': {
      id: '/_client/dashboard/usage'
      path: '/usage'
      fullPath: '/dashboard/usage'
      preLoaderRoute: typeof ClientDashboardUsageRouteImport
      parentRoute: typeof ClientDashboardRoute
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AdminProvidersRouteChildren {
  AdminProvidersIndexRoute: typeof AdminProvidersIndexRoute
  AdminProvidersProviderIdRoute: typeof AdminProvidersProviderIdRoute
}

const AdminProvidersRouteChildren: AdminProvidersRouteChildren = {
  AdminProvidersIndexRoute: AdminProvidersIndexRoute,
  AdminProvidersProviderIdRoute: AdminProvidersProviderIdRoute,
}

const AdminProvidersRouteWithChildren = AdminProvidersRoute._addFileChildren(
  AdminProvidersRouteChildren,
)

interface AdminRouteChildren {
  AdminIndexRoute: typeof AdminIndexRoute
  AdminAnalyticsRoute: typeof AdminAnalyticsRoute
  AdminComboRoute: typeof AdminComboRoute
  AdminKeysRoute: typeof AdminKeysRoute
  AdminLogsRoute: typeof AdminLogsRoute
  AdminProvidersRoute: typeof AdminProvidersRouteWithChildren
  AdminQuotaRoute: typeof AdminQuotaRoute
  AdminSettingsRoute: typeof AdminSettingsRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminIndexRoute: AdminIndexRoute,
  AdminAnalyticsRoute: AdminAnalyticsRoute,
  AdminComboRoute: AdminComboRoute,
  AdminKeysRoute: AdminKeysRoute,
  AdminLogsRoute: AdminLogsRoute,
  AdminProvidersRoute: AdminProvidersRouteWithChildren,
  AdminQuotaRoute: AdminQuotaRoute,
  AdminSettingsRoute: AdminSettingsRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface ClientDashboardRouteChildren {
  ClientDashboardIndexRoute: typeof ClientDashboardIndexRoute
  ClientDashboardKeysRoute: typeof ClientDashboardKeysRoute
  ClientDashboardUsageRoute: typeof ClientDashboardUsageRoute
}

const ClientDashboardRouteChildren: ClientDashboardRouteChildren = {
  ClientDashboardIndexRoute: ClientDashboardIndexRoute,
  ClientDashboardKeysRoute: ClientDashboardKeysRoute,
  ClientDashboardUsageRoute: ClientDashboardUsageRoute,
}

const ClientDashboardRouteWithChildren = ClientDashboardRoute._addFileChildren(
  ClientDashboardRouteChildren,
)

interface ClientRouteChildren {
  ClientDashboardRoute: typeof ClientDashboardRouteWithChildren
}

const ClientRouteChildren: ClientRouteChildren = {
  ClientDashboardRoute: ClientDashboardRouteWithChildren,
}

const ClientRouteWithChildren = ClientRoute._addFileChildren(ClientRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AdminRoute: AdminRouteWithChildren,
  ClientRoute: ClientRouteWithChildren,
  LoginRoute: LoginRoute,
  RegisterRoute: RegisterRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
